function analyze_time_domain(config_path)
%ANALYZE_TIME_DOMAIN Compute discrete metrics from simulation outputs.
%   ANALYZE_TIME_DOMAIN(CONFIG_PATH) loads the raw MAT files generated by
%   run_simulation.m, recomputes error integrals, validates them against the
%   Simulink integrator outputs, extracts time-domain characteristics using
%   stepinfo/lsiminfo, and writes the consolidated metrics to metrics.json.
arguments
    config_path (1, :) char = 'config/sim_config.json'
end

script_dir = fileparts(mfilename('fullpath'));
project_root = fileparts(script_dir);
addpath(script_dir);
addpath(fullfile(project_root, 'util'));

cfg = jsondecode(fileread(config_path));
run_root = fullfile(cfg.simulation.artifact_root, cfg.simulation.run_id);
raw_dir = fullfile(run_root, 'raw');
if ~exist(raw_dir, 'dir') %#ok<EXIST>
    error('analyze_time_domain:MissingRaw', ...
        'Raw directory %s does not exist. Run run_simulation first.', raw_dir);
end

Ts = cfg.Ts;
ref_sig = load_structure(fullfile(raw_dir, 'ref_sig.mat'));
y_pid_sig = load_structure(fullfile(raw_dir, 'y_pid_sig.mat'));
y_lstm_sig = load_structure(fullfile(raw_dir, 'y_lstm_sig.mat'));
e_pid = load_structure(fullfile(raw_dir, 'e_pid.mat'));
e_lstm = load_structure(fullfile(raw_dir, 'e_lstm.mat'));

integrals = struct();
integrals.iae.pid = compute_integral(e_pid.signals.values, Ts, 'abs');
integrals.iae.lstm = compute_integral(e_lstm.signals.values, Ts, 'abs');
integrals.ise.pid = compute_integral(e_pid.signals.values, Ts, 'square');
integrals.ise.lstm = compute_integral(e_lstm.signals.values, Ts, 'square');
integrals.itae.pid = compute_integral(e_pid.signals.values, Ts, 'itae', e_pid.time);
integrals.itae.lstm = compute_integral(e_lstm.signals.values, Ts, 'itae', e_lstm.time);

validate_integrals(raw_dir, integrals, 1e-9);

time_info = extract_time_domain_metrics(ref_sig, y_pid_sig, y_lstm_sig, cfg);

timing_error = struct();
final_time = ref_sig.time(end);
selected_channel = time_info.channel;
timing_error.pid = compute_timing_error(ref_sig, y_pid_sig, final_time, selected_channel);
timing_error.lstm = compute_timing_error(ref_sig, y_lstm_sig, final_time, selected_channel);

metrics = struct();
metrics.iae = integrals.iae;
metrics.ise = integrals.ise;
metrics.itae = integrals.itae;
metrics.time_domain = time_info;
metrics.timing_error_sum = timing_error;
metrics.metadata = struct( ...
    'config_path', config_path, ...
    'run_root', run_root, ...
    'channel_index', time_info.channel, ...
    'analysis_tolerance', 1e-9, ...
    'git_hash', get_git_revision());
metrics.metadata = orderfields(metrics.metadata);
metrics.time_domain = rmfield(metrics.time_domain, 'channel');
metrics.time_domain = orderfields(metrics.time_domain);

metrics_path = fullfile(run_root, 'metrics.json');
json_text = jsonencode(metrics, 'PrettyPrint', true);
fid = fopen(metrics_path, 'w');
if fid == -1
    error('analyze_time_domain:FileOpenFailed', ...
        'Unable to open %s for writing.', metrics_path);
end
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, json_text, 'char');
clear cleanup;

end

function structure = load_structure(path)
if ~exist(path, 'file') %#ok<EXIST>
    error('analyze_time_domain:MissingFile', 'Expected MAT file %s.', path);
end
payload = load(path);
if isfield(payload, 'time') && isfield(payload, 'signals')
    structure = payload;
else
    fields = fieldnames(payload);
    if numel(fields) == 1
        structure = payload.(fields{1});
    else
        error('analyze_time_domain:InvalidMatFile', ...
            'MAT file %s must contain time/signals fields.', path);
    end
end
if ~isfield(structure, 'time') || ~isfield(structure, 'signals')
    error('analyze_time_domain:InvalidStructure', ...
        'MAT file %s lacks time/signals fields.', path);
end
structure.time = double(structure.time(:));
structure.signals.values = double(structure.signals.values);
end

function value = compute_integral(values, Ts, mode, time_vector)
arguments
    values double
    Ts double
    mode (1, :) char
    time_vector double = []
end

switch lower(mode)
    case 'abs'
        sample_metric = sum(abs(values), 2);
        value = sum(sample_metric) * Ts;
    case 'square'
        sample_metric = sum(values.^2, 2);
        value = sum(sample_metric) * Ts;
    case 'itae'
        if isempty(time_vector)
            error('compute_integral:MissingTime', 'Time vector required for ITAE.');
        end
        sample_metric = sum(abs(values), 2);
        value = sum(time_vector(:) .* sample_metric) * Ts;
    otherwise
        error('compute_integral:UnknownMode', 'Unsupported mode %s.', mode);
end
end

function validate_integrals(raw_dir, integrals, tolerance)
signals = fieldnames(integrals);
for i = 1:numel(signals)
    metric = signals{i};
    channels = fieldnames(integrals.(metric));
    for j = 1:numel(channels)
        controller = channels{j};
        mat_path = fullfile(raw_dir, sprintf('%s_%s.mat', metric, controller));
        mat_struct = load_structure(mat_path);
        sim_value = mat_struct.signals.values(end);
        diff_val = abs(sim_value - integrals.(metric).(controller));
        if diff_val > tolerance
            error('analyze_time_domain:IntegralMismatch', ...
                '%s_%s differs by %.3g (tolerance %.3g).', ...
                metric, controller, diff_val, tolerance);
        end
    end
end
end

function info = extract_time_domain_metrics(ref_sig, y_pid_sig, y_lstm_sig, cfg)
info_spec = choose_info_fn(ref_sig);
settling_threshold = cfg.check.settling_percentage / 100.0;
channel = info_spec.channel;
time = ref_sig.time;
ref_channel = ref_sig.signals.values(:, channel);
pid_channel = y_pid_sig.signals.values(:, channel);
lstm_channel = y_lstm_sig.signals.values(:, channel);

if strcmp(info_spec.type, 'step')
    pid_info = info_spec.handle(pid_channel, time, 'SettlingTimeThreshold', settling_threshold);
    lstm_info = info_spec.handle(lstm_channel, time, 'SettlingTimeThreshold', settling_threshold);
else
    pid_info = info_spec.handle(pid_channel, time, ref_channel, 'SettlingTimeThreshold', settling_threshold);
    lstm_info = info_spec.handle(lstm_channel, time, ref_channel, 'SettlingTimeThreshold', settling_threshold);
end

info = struct();
info.channel = channel;
info.pid = filter_time_info(pid_info);
info.lstm = filter_time_info(lstm_info);
end

function filtered = filter_time_info(raw_info)
fields = {'RiseTime', 'SettlingTime', 'Overshoot', 'Peak', 'PeakTime'};
filtered = struct();
for i = 1:numel(fields)
    key = fields{i};
    if isfield(raw_info, key)
        filtered.(key) = raw_info.(key);
    else
        filtered.(key) = NaN;
    end
end
filtered = orderfields(filtered);
end

function timing_error = compute_timing_error(ref_sig, output_sig, final_time, channel)
ref_events = detect_events(ref_sig, channel);
out_events = detect_events(output_sig, channel);
count = min(numel(ref_events), numel(out_events));
err = sum(abs(ref_events(1:count) - out_events(1:count)));
if numel(ref_events) > count
    err = err + sum(abs(ref_events(count+1:end) - final_time));
elseif numel(out_events) > count
    err = err + sum(abs(out_events(count+1:end) - final_time));
end
timing_error = err;
end

function events = detect_events(signal, channel)
values = signal.signals.values(:, channel);
threshold = 0.5;
active = values > threshold;
transitions = find(diff([0; active]) > 0.5);
if isempty(transitions)
    events = [];
else
    events = signal.time(transitions);
end
end

function hash = get_git_revision()
[status, output] = system('git rev-parse HEAD');
if status ~= 0
    hash = 'unknown';
else
    hash = strtrim(output);
end
end
